# === Match ===================================================================
[Match]
distribution
#Release=general
Architecture=x86-64
Environment=!EDITION=desktop

# === Distribution ============================================================
[Distribution]
RepositoryKeyCheck=no
RepositoryKeyFetch=yes
#Repositories=

# === Output ==================================================================
[Output]
Output=rootfs
OutputDirectory=$SUDO_HOME/.workdirs/mkosi/%d-%r-%a-$EDITION/outputs/
#Format=disk
#Format=directory
#CompressOutput=zstd

# === Build ===================================================================
[Build]
WorkspaceDirectory=$SUDO_HOME/.workdirs/mkosi/%d-%r-%a-$EDITION/workdir/
PackageCacheDirectory=/srv/user/share/cache/%d-%r-%a
ToolsTree=yes
WithNetwork=yes
#SandboxTrees=
#CacheDirectory=/srv/user/share/cache/
#CacheKey=%d-%r-%a
#BuildSources=$SUDO_HOME/.workdirs/mkosi/%d-%r-%a-$EDITION/sources/
#BuildSources=$SUDO_HOME/.workdirs/mkosi/%d-%r-%a/sources/
#BuildKey=%d-%r-%a

# === Runtime =================================================================
[Runtime]
Machine=pc-%d-%r-%a

# === Validation ==============================================================
[Validation]
SecureBoot=no

# === Content =================================================================
[Content]
# --- user --------------------------------------------------------------------
RootPassword=r00t
#Autologin=yes
# --- locale ------------------------------------------------------------------
Locale=ja_JP.UTF-8
LocaleMessages=ja_JP.UTF-8
Keymap=jp
Timezone=Asia/Tokyo
# --- host --------------------------------------------------------------------
Hostname=sv-%d.workgroup
RootShell=/bin/bash
SELinuxRelabel=no
Bootable=no
# --- initramfs ---------------------------------------------------------------
#MakeInitrd=yes
#InitrdPackages=
# --- install -----------------------------------------------------------------
WithRecommends=yes
#SyncScripts=mkosi.builddir/add-backports.sh
#SyncScripts=base/add-backports.sh
Packages=
    # --- mkosi ---------------------------------------------------------------
    # --- kernel --------------------------------------------------------------
    # --- microcode -----------------------------------------------------------
    # --- grub ----------------------------------------------------------------
    # --- development ---------------------------------------------------------
    # --- dracut --------------------------------------------------------------
    # --- dracut install modules ----------------------------------------------
    # --- qemu ----------------------------------------------------------------
    # --- server (from the preconfiguration file) -----------------------------
    # --- desktop (from the preconfiguration file) ----------------------------
    # --- installation environment --------------------------------------------
    # -------------------------------------------------------------------------

# === eof =====================================================================
