# shellcheck disable=SC2148

# -----------------------------------------------------------------------------
# descript: resolv.conf
#   input :            : unused
#   output:   stdout   : message
#   return:            : unused
#   g-var :            : unused
# shellcheck disable=SC2148,SC2317,SC2329
fnSetup_resolv() {
	__FUNC_NAME="fnSetup_resolv"
	fnMsgout "${_PROG_NAME:-}" "start" "[${__FUNC_NAME}]"

	# --- check command -------------------------------------------------------
	__PATH="${_DIRS_TGET:-}/etc/resolv.conf"
	fnFile_backup "${__PATH}"			# backup original file
	mkdir -p "${__PATH%/*}"
	if ! command -v resolvectl > /dev/null 2>&1; then
		if [ ! -h "${__PATH}" ]; then
			cp --preserve=timestamps "${_DIRS_ORIG}/${__PATH#*"${_DIRS_TGET:-}/"}" "${__PATH}"
			cat <<- _EOT_ | sed -e '/^ [^ ]\+/ s/^ *//g' -e 's/^ \+$//g' >> "${__PATH}"
				# Generated by user script
				search ${_NICS_WGRP}
				nameserver ${_IPV6_LHST}
				nameserver ${_IPV4_LHST}
_EOT_
		fi
		fnDbgdump "${__PATH}"				# debugout
		fnFile_backup "${__PATH}" "init"	# backup initial file
	else
		__CONF="${_DIRS_TGET:-}/run/systemd/resolve/stub-resolv.conf"
		fnFile_backup "${__CONF}"			# backup original file
#		if grep -qi 'Do not edit.' "${__PATH}"; then
#			fnMsgout "${_PROG_NAME:-}" "skip" "resolv.conf setup for chroot"
#		else
#			mkdir -p "${__CONF%/*}"
#			cp --preserve=timestamps "${_DIRS_ORIG}/${__CONF#*"${_DIRS_TGET:-}/"}" "${__CONF}"
			if [ ! -h "${__PATH}" ]; then
				rm -f "${__PATH}"
				ln -s "../${__CONF#"${_DIRS_TGET:-}/"}" "${__PATH}"
			fi
			fnDbgdump "${__PATH}"				# debugout
			fnFile_backup "${__PATH}" "init"	# backup initial file
			fnFile_backup "${__CONF}" "init"	# backup initial file
#		fi
		# --- default.conf ----------------------------------------------------
		__PATH="${_DIRS_TGET:-}/etc/systemd/resolved.conf.d/default.conf"
		fnFile_backup "${__PATH}"			# backup original file
		mkdir -p "${__PATH%/*}"
		cp --preserve=timestamps "${_DIRS_ORIG}/${__PATH#*"${_DIRS_TGET:-}/"}" "${__PATH}"
		cat <<- _EOT_ | sed -e '/^ [^ ]\+/ s/^ *//g' -e 's/^ \+$//g' >> "${__PATH}"
			[Resolve]
			MulticastDNS=yes
			DNS=${_NICS_DNS4}
			Domains=${_NICS_WGRP}
_EOT_
		fnDbgdump "${__PATH}"				# debugout
		fnFile_backup "${__PATH}" "init"	# backup initial file
		# --- service restart -------------------------------------------------
		__SRVC="systemd-resolved.service"
		if systemctl --quiet is-enabled "${__SRVC}"; then
			__SVEX="avahi-daemon.service"
			if systemctl --quiet is-enabled "${__SVEX}"; then
				fnMsgout "${_PROG_NAME:-}" "mask" "${__SVEX}"
				systemctl --quiet mask "${__SVEX}"
				systemctl --quiet mask "${__SVEX%.*}.socket"
			fi
		fi
		if [ -z "${_TGET_CNTR:-}" ]; then
			if systemctl --quiet is-active "${__SRVC}"; then
				fnMsgout "${_PROG_NAME:-}" "restart" "${__SRVC}"
				systemctl --quiet daemon-reload
				if systemctl --quiet restart "${__SRVC}"; then
					fnMsgout "${_PROG_NAME:-}" "success" "${__SRVC}"
				else
					fnMsgout "${_PROG_NAME:-}" "failed" "${__SRVC}"
				fi
			fi
		fi
	fi
	unset __PATH __CONF __SRVC __SVEX

	# --- complete ------------------------------------------------------------
	fnMsgout "${_PROG_NAME:-}" "complete" "[${__FUNC_NAME}]" 
	unset __FUNC_NAME
}
