# shellcheck disable=SC2148

# -----------------------------------------------------------------------------
# descript: connman
#   input :            : unused
#   output:   stdout   : message
#   return:            : unused
#   g-var :            : unused
# shellcheck disable=SC2148,SC2317,SC2329
fnSetup_connman() {
	__FUNC_NAME="fnSetup_connman"
	fnMsgout "start" "[${__FUNC_NAME}]"

	# --- check command -------------------------------------------------------
	if ! command -v connmanctl > /dev/null 2>&1; then
		fnMsgout "skip" "[${__FUNC_NAME}]"
		return
	fi
	# --- main.conf -----------------------------------------------------------
	__PATH="${_DIRS_TGET:-}/etc/connman/main.conf"
	fnFile_backup "${__PATH}"			# backup original file
	mkdir -p "${__PATH%/*}"
	cp -a "${_DIRS_ORIG}/${__PATH#*"${_DIRS_TGET:-}/"}" "${__PATH}"
	cat <<- _EOT_ | sed -e '/^ [^ ]\+/ s/^ *//g' -e 's/^ \+$//g' >> "${__PATH}"

		# Generated by user script
		AllowHostnameUpdates = false
		AllowDomainnameUpdates = false
		PreferredTechnologies = ethernet,wifi
		SingleConnectedTechnology = true
_EOT_
	fnDbgdump "${__PATH}"				# debugout
	fnFile_backup "${__PATH}" "init"	# backup initial file
	# --- disable_dns_proxy.conf ----------------------------------------------
	__WORK="$(command -v connmand 2> /dev/null)"
	__PATH="${_DIRS_TGET:-}/etc/systemd/system/connman.service.d/disable_dns_proxy.conf"
	fnFile_backup "${__PATH}"			# backup original file
	mkdir -p "${__PATH%/*}"
	cp -a "${_DIRS_ORIG}/${__PATH#*"${_DIRS_TGET:-}/"}" "${__PATH}"
	cat <<- _EOT_ | sed -e '/^ [^ ]\+/ s/^ *//g' -e 's/^ \+$//g' > "${__PATH}"
		[Service]
		ExecStart=
		ExecStart=${__WORK} -n --nodnsproxy
_EOT_
	fnDbgdump "${__PATH}"				# debugout
	fnFile_backup "${__PATH}" "init"	# backup initial file
	# --- settings ------------------------------------------------------------
	__PATH="${_DIRS_TGET:-}/var/lib/connman/ethernet_${_NICS_MADR//:/}_cable/settings"
	fnFile_backup "${__PATH}"			# backup original file
	mkdir -p "${__PATH%/*}"
	cp -a "${_DIRS_ORIG}/${__PATH#*"${_DIRS_TGET:-}/"}" "${__PATH}"
	cat <<- _EOT_ | sed -e '/^ [^ ]\+/ s/^ *//g' -e 's/^ \+$//g' > "${__PATH}"
			[ethernet_${_NICS_MADR//:/}_cable]
			Name=Wired
			AutoConnect=true
			Modified=
_EOT_
	if [ -n "${_NICS_AUTO##-}" ]; then
		cat <<- _EOT_ | sed -e '/^ [^ ]\+/ s/^ *//g' -e 's/^ \+$//g' >> "${__PATH}"
			IPv4.method=dhcp
			IPv4.DHCP.LastAddress=
			IPv6.method=auto
			IPv6.privacy=prefered
_EOT_
	else
		cat <<- _EOT_ | sed -e '/^ [^ ]\+/ s/^ *//g' -e 's/^ \+$//g' >> "${__PATH}"
			IPv4.method=manual
			IPv4.netmask_prefixlen=${_NICS_BIT4}
			IPv4.local_address=${_NICS_IPV4}
			IPv4.gateway=${_NICS_GATE}
			IPv6.method=auto
			IPv6.privacy=prefered
			Nameservers=${_NICS_DNS4};
			Domains=${_NICS_WGRP};
			IPv6.DHCP.DUID=
_EOT_
	fi
	chmod 600 "${__PATH}"
	fnDbgdump "${__PATH}"				# debugout
	fnFile_backup "${__PATH}" "init"	# backup initial file
	# --- service restart -----------------------------------------------------
	__SRVC="wireplumber.service"
	if systemctl --quiet is-active "${__SRVC}"; then
		fnMsgout "restart" "${__SRVC}"
		systemctl --quiet daemon-reload
		if systemctl --quiet restart "${__SRVC}"; then
			fnMsgout "success" "${__SRVC}"
		else
			fnMsgout "failed" "${__SRVC}"
		fi
	fi

	# --- complete ------------------------------------------------------------
	fnMsgout "complete" "[${__FUNC_NAME}]" 
}
