"""Common Function Package: utils [generated: 2026/09/28 12:54:38 JST (+0900)]"""

# ruff: isort: off
from . import my_env_guard

del my_env_guard
# ruff: isort: on

# --- Python library ----------------------------------------------------------
import importlib  # noqa: E402


# --- my library --------------------------------------------------------------
__all__ = [
    "infosystem",
    "Argument",
    "Code",
    "Color",
    "DebugLogWindow",
    "Emoji",
    "FileData",
    "InfoFile",
    "InfoSystem",
    "InfoWeb",
    "SystemData",
    "TimeElapsed",
    "WebData",
    "_compile_exclude_regex",
    "_expand_regexp_urls",
    "build_buttons",
    "build_menu_bar",
    "count_full_width",
    "count_half_width",
    "count_width",
    "debug_chk_cui",
    "debug_logger",
    "debugout",
    "debugout_scale",
    "detect_language",
    "eprint",
    "file_backup",
    "file_copy",
    "file_read",
    "file_write",
    "generate_comment",
    "generate_wget_filename",
    "get_caller_name",
    "get_char_width",
    "get_contents",
    "get_header",
    "get_info",
    "get_infoweb",
    "get_peak_memory",
    "get_response",
    "get_volume_label",
    "get_volume_uuid",
    "handle_fatal_error",
    "json_load",
    "json_save",
    "list2markdown",
    "load_ui_definition",
    "markdown2list",
    "message_alert",
    "message_debug",
    "message_elapsed",
    "message_end",
    "message_info",
    "message_out",
    "message_start",
    "message_warn",
    "omit_middle",
    "print_peak_memory",
    "remove_gui_log_window",
    "run_subprocess",
    "set_gui_log_window",
    "split_by_width",
]

_MODULE_MAP = {
    "infosystem": ".my_config",
    "Argument": ".my_argument",
    "Code": ".my_colors",
    "Color": ".my_colors",
    "DebugLogWindow": ".my_gui_build_log_monitor",
    "Emoji": ".my_colors",
    "FileData": ".my_infofile",
    "InfoFile": ".my_infofile",
    "InfoSystem": ".my_config",
    "InfoWeb": ".my_infoweb",
    "SystemData": ".my_config",
    "TimeElapsed": ".my_time",
    "WebData": ".my_web_api",
    "_compile_exclude_regex": ".my_infoweb",
    "_expand_regexp_urls": ".my_infoweb",
    "build_buttons": ".my_gui_build_helper",
    "build_menu_bar": ".my_gui_build_helper",
    "count_full_width": ".my_string",
    "count_half_width": ".my_string",
    "count_width": ".my_string",
    "debug_chk_cui": ".my_debug",
    "debug_logger": ".my_debug",
    "debugout": ".my_debug",
    "debugout_scale": ".my_debug",
    "detect_language": ".my_language",
    "eprint": ".my_string",
    "file_backup": ".my_file_api",
    "file_copy": ".my_file_api",
    "file_read": ".my_file_api",
    "file_write": ".my_file_api",
    "generate_comment": ".my_message",
    "generate_wget_filename": ".my_web_api",
    "get_caller_name": ".my_message",
    "get_char_width": ".my_string",
    "get_contents": ".my_web_api",
    "get_header": ".my_web_api",
    "get_info": ".my_infofile",
    "get_infoweb": ".my_infoweb",
    "get_peak_memory": ".my_mem_usage",
    "get_response": ".my_web_api",
    "get_volume_label": ".my_infofile",
    "get_volume_uuid": ".my_infofile",
    "handle_fatal_error": ".my_error",
    "json_load": ".my_json",
    "json_save": ".my_json",
    "list2markdown": ".my_markdown",
    "load_ui_definition": ".my_gui_build_helper",
    "markdown2list": ".my_markdown",
    "message_alert": ".my_message",
    "message_debug": ".my_message",
    "message_elapsed": ".my_message",
    "message_end": ".my_message",
    "message_info": ".my_message",
    "message_out": ".my_message",
    "message_start": ".my_message",
    "message_warn": ".my_message",
    "omit_middle": ".my_string",
    "print_peak_memory": ".my_mem_usage",
    "remove_gui_log_window": ".my_string",
    "run_subprocess": ".my_process",
    "set_gui_log_window": ".my_string",
    "split_by_width": ".my_string",
}


def __getattr__(name):
    if name in _MODULE_MAP:
        module = importlib.import_module(_MODULE_MAP[name], __name__)
        return getattr(module, name)
    raise AttributeError(f"module {__name__} has no attribute {name}")
